import cv2
import os
import numpy as np
from PIL import Image

from tools.data.file_ops import get_project_root, generate_random_filename, create_directory_if_not_exists, \
    convert_prompt_to_filename


def read_image(image_path, mode='rgb'):
    """
    Read image from file.
    :param image_path: iamge file path
    :param mode: str, image format，'rgb', 'bgr' and 'gray' are supported
    :return: numpy.ndarray, dtype=np.uint8, shape=(h, w, c)
    """
    assert mode in ['rgb', 'bgr', 'gray'], "mode must be one of 'rgb', 'bgr', 'gray'"
    image_array = cv2.imread(image_path, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
    if mode == "rgb":
        return cv2.cvtColor(image_array, cv2.COLOR_BGR2RGB)
    elif mode == 'gray':
        gray = cv2.cvtColor(image_array, cv2.COLOR_BGR2GRAY)
        gray = np.expand_dims(gray, axis=-1)
        return gray
    else:
        # default "bgr"
        return image_array


def save_image(image, save_folder, filename=None):
    """
    Save image to file.
    :param image: numpy.ndarray，image that read by opencv.
    :param save_folder:
    :param filename:
    :return:
    """
    if not filename:
        filename = generate_random_filename("img", "png")
    _ = create_directory_if_not_exists(save_folder)
    save_path = os.path.join(get_project_root(), save_folder, filename)
    if isinstance(image, np.ndarray):
        cv2.imwrite(save_path, image)
    elif isinstance(image, Image.Image):
        image.save(fp=save_path)
    else:
        raise ValueError(f"Unsupported image type.")
    print(f"Saved to {save_path}.")


def save_ai_generated_image(image, save_folder, prompt):
    """
    Save the image generated by AI, and the image name is related to prompt.
    :param image: PIL.Image.Image,
    :param save_folder: str,
    :param prompt: str,
    :return:
    """
    assert isinstance(image, Image.Image)

    filename_prefix = convert_prompt_to_filename(prompt)
    filename = generate_random_filename(file_type=filename_prefix, suffix="png")
    save_dir = create_directory_if_not_exists(save_folder)
    save_dir = os.path.join(save_dir, filename)
    image.save(fp=save_dir)
    print(f"Saved to {save_dir}.")
